import json
import os

cells = [

# ── SECTION 0: Title
{"cell_type": "markdown", "metadata": {}, "source": ["# 30-Day Patient Readmission Prediction\n## Improved Deep Learning Pipeline\n\nThis notebook covers an advanced pipeline:\n1. Data Loading & Initial Inspection\n2. Exploratory Data Analysis (EDA)\n3. Data Cleaning & Feature Engineering\n4. Missing Value Imputation\n5. Class Imbalance Analysis & Encoding\n6. SMOTE Oversampling\n7. Advanced Model Training (Deeper PyTorch Network with Focal Loss)\n8. Evaluation & Threshold Tuning\n9. Test Set Predictions"]},

# ── SECTION 1: Imports
{"cell_type": "markdown", "metadata": {}, "source": ["## 1. Imports & Setup"]},
{"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "# Core\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "\n",
    "# Visualization\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "sns.set(style=\"whitegrid\")\n",
    "\n",
    "# Sklearn\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics import (\n",
    "    classification_report, confusion_matrix, roc_auc_score,\n",
    "    average_precision_score, f1_score, precision_recall_curve,\n",
    "    roc_curve, precision_score, recall_score\n",
    ")\n",
    "\n",
    "# Imbalanced-learn\n",
    "from imblearn.over_sampling import SMOTE\n",
    "\n",
    "# PyTorch\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "import torch.nn.functional as F\n",
    "from torch.utils.data import DataLoader, TensorDataset\n",
    "\n",
    "# Settings\n",
    "pd.set_option(\"display.max_columns\", None)\n",
    "RANDOM_STATE = 42\n",
    "np.random.seed(RANDOM_STATE)\n",
    "torch.manual_seed(RANDOM_STATE)\n",
    "if torch.cuda.is_available():\n",
    "    torch.cuda.manual_seed_all(RANDOM_STATE)\n",
    "print(\"All imports successful!\")"
]},

# ── SECTION 2 & 3: Load Data & Preprocessing (Combined for brevity)
{"cell_type": "markdown", "metadata": {}, "source": ["## 2. Load & Clean Data"]},
{"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "# Load raw datasets\n",
    "train_df = pd.read_csv(\"../data/train.csv\")\n",
    "test_df  = pd.read_csv(\"../data/test.csv\")\n",
    "\n",
    "# 1. Drop patient ID\n",
    "train_df.drop(columns=[\"patient_id\"], inplace=True, errors=\"ignore\")\n",
    "test_df.drop(columns=[\"patient_id\"], inplace=True, errors=\"ignore\")\n",
    "\n",
    "# 2. Age Outliers\n",
    "train_df[\"age\"] = train_df[\"age\"].replace(999, np.nan)\n",
    "test_df[\"age\"]  = test_df[\"age\"].replace(999, np.nan)\n",
    "\n",
    "# 3. BP Fix\n",
    "mask_train = train_df[\"blood_pressure_systolic\"] < 50\n",
    "train_df.loc[mask_train, \"blood_pressure_systolic\"] *= 7.50062\n",
    "mask_test = test_df[\"blood_pressure_systolic\"] < 50\n",
    "test_df.loc[mask_test, \"blood_pressure_systolic\"] *= 7.50062\n",
    "\n",
    "# 4. Dates\n",
    "for df in [train_df, test_df]:\n",
    "    if \"admission_date\" in df.columns:\n",
    "        df[\"admission_date\"] = pd.to_datetime(\n",
    "            df[\"admission_date\"], format=\"mixed\", dayfirst=True, errors=\"coerce\"\n",
    "        )\n",
    "        df[\"admission_month\"]   = df[\"admission_date\"].dt.month\n",
    "        df[\"admission_day\"]     = df[\"admission_date\"].dt.day\n",
    "        df[\"admission_weekday\"] = df[\"admission_date\"].dt.weekday\n",
    "        df.drop(columns=[\"admission_date\"], inplace=True)\n",
    "\n",
    "# 5. Missing Values (Glucose Info + Medians)\n",
    "train_df[\"glucose_missing\"] = train_df[\"glucose_level_mgdl\"].isnull().astype(int)\n",
    "test_df[\"glucose_missing\"]  = test_df[\"glucose_level_mgdl\"].isnull().astype(int)\n",
    "age_median     = train_df[\"age\"].median()\n",
    "glucose_median = train_df[\"glucose_level_mgdl\"].median()\n",
    "for df in [train_df, test_df]:\n",
    "    df[\"age\"].fillna(age_median, inplace=True)\n",
    "    df[\"glucose_level_mgdl\"].fillna(glucose_median, inplace=True)\n",
    "\n",
    "# 6. Encoding\n",
    "train_df[\"gender\"] = (train_df[\"gender\"] == \"M\").astype(int)\n",
    "test_df[\"gender\"]  = (test_df[\"gender\"] == \"M\").astype(int)\n",
    "\n",
    "train_ins = pd.get_dummies(train_df[\"insurance_type\"], prefix=\"ins\")\n",
    "test_ins  = pd.get_dummies(test_df[\"insurance_type\"], prefix=\"ins\")\n",
    "for col in train_ins.columns:\n",
    "    if col not in test_ins.columns: test_ins[col] = 0\n",
    "test_ins = test_ins[train_ins.columns]\n",
    "train_df = pd.concat([train_df.drop(columns=[\"insurance_type\"]), train_ins], axis=1)\n",
    "test_df  = pd.concat([test_df.drop(columns=[\"insurance_type\"]), test_ins], axis=1)\n",
    "\n",
    "train_day = pd.get_dummies(train_df[\"discharge_day_of_week\"], prefix=\"day\")\n",
    "test_day  = pd.get_dummies(test_df[\"discharge_day_of_week\"], prefix=\"day\")\n",
    "for col in train_day.columns:\n",
    "    if col not in test_day.columns: test_day[col] = 0\n",
    "test_day = test_day[train_day.columns]\n",
    "train_df = pd.concat([train_df.drop(columns=[\"discharge_day_of_week\"]), train_day], axis=1)\n",
    "test_df  = pd.concat([test_df.drop(columns=[\"discharge_day_of_week\"]), test_day], axis=1)\n",
    "\n",
    "print(\"✅ Data cleaned and encoded!\")\n",
    "print(f\"Train shape: {train_df.shape}\")\n",
    "print(f\"Test shape:  {test_df.shape}\")"
]},

# ── SECTION 3: Split & Scale
{"cell_type": "markdown", "metadata": {}, "source": ["## 3. Train / Validation Split & Scaling"]},
{"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "TARGET = \"readmitted_30d\"\n",
    "\n",
    "y_full    = train_df[TARGET].values\n",
    "X_full_df = train_df.drop(columns=[TARGET])\n",
    "X_test_df = test_df.copy()\n",
    "\n",
    "# Align column order between train features and test\n",
    "for col in X_full_df.columns:\n",
    "    if col not in X_test_df.columns:\n",
    "        X_test_df[col] = 0\n",
    "X_test_df = X_test_df[X_full_df.columns]\n",
    "\n",
    "X_train, X_val, y_train, y_val = train_test_split(\n",
    "    X_full_df, y_full,\n",
    "    test_size=0.2,\n",
    "    random_state=RANDOM_STATE,\n",
    "    stratify=y_full\n",
    ")\n",
    "\n",
    "# Scale numeric features (fit on train ONLY to prevent leakage)\n",
    "numeric_cols = [\n",
    "    \"age\", \"admission_type\", \"discharge_destination\",\n",
    "    \"length_of_stay_days\", \"charlson_comorbidity_index\",\n",
    "    \"prior_admissions_1yr\", \"n_medications_discharge\",\n",
    "    \"glucose_level_mgdl\", \"blood_pressure_systolic\",\n",
    "    \"sodium_meql\", \"creatinine_mgdl\", \"haemoglobin_gdl\",\n",
    "    \"admission_month\", \"admission_day\", \"admission_weekday\"\n",
    "]\n",
    "numeric_cols = [c for c in numeric_cols if c in X_train.columns]\n",
    "\n",
    "scaler = StandardScaler()\n",
    "X_train_sec = X_train.copy()\n",
    "X_val_sec = X_val.copy()\n",
    "X_test_sec = X_test_df.copy()\n",
    "\n",
    "X_train_sec[numeric_cols] = scaler.fit_transform(X_train[numeric_cols])\n",
    "X_val_sec[numeric_cols]   = scaler.transform(X_val[numeric_cols])\n",
    "X_test_sec[numeric_cols]  = scaler.transform(X_test_df[numeric_cols])\n",
    "\n",
    "X_train = X_train_sec.values\n",
    "X_val = X_val_sec.values\n",
    "X_test_df = X_test_sec\n",
    "\n",
    "print(\"✅ Matrices split and scaled.\")"
]},

# ── SECTION 4: SMOTE
{"cell_type": "markdown", "metadata": {}, "source": ["## 4. Class Imbalance Mitigation – SMOTE"]},
{"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "smote = SMOTE(random_state=RANDOM_STATE, sampling_strategy=0.6)  # Slightly more aggressive oversampling\n",
    "X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)\n",
    "\n",
    "print(f\"Before SMOTE: {X_train.shape[0]} samples, pos ratio: {y_train.mean():.4f}\")\n",
    "print(f\"After  SMOTE: {X_train_sm.shape[0]} samples, pos ratio: {y_train_sm.mean():.4f}\")"
]},

# ── SECTION 5: PyTorch datasets
{"cell_type": "markdown", "metadata": {}, "source": ["## 5. Prepare PyTorch Datasets"]},
{"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "# Cast to float32 to avoid numpy object-array issues\n",
    "X_train_t = torch.FloatTensor(X_train_sm.astype(np.float32))\n",
    "y_train_t = torch.FloatTensor(y_train_sm.astype(np.float32))\n",
    "X_val_t   = torch.FloatTensor(X_val.astype(np.float32))\n",
    "y_val_t   = torch.FloatTensor(y_val.astype(np.float32))\n",
    "X_test_t  = torch.FloatTensor(X_test_df.values.astype(np.float32))\n",
    "\n",
    "BATCH_SIZE   = 128  # Increased batch size for more stable gradients with deeper network\n",
    "train_loader = DataLoader(TensorDataset(X_train_t, y_train_t), batch_size=BATCH_SIZE, shuffle=True)\n",
    "val_loader   = DataLoader(TensorDataset(X_val_t, y_val_t), batch_size=BATCH_SIZE, shuffle=False)\n",
    "\n",
    "INPUT_DIM = X_train_t.shape[1]\n",
    "print(f\"Input features: {INPUT_DIM}\")"
]},

# ── SECTION 6: Improved Model
{"cell_type": "markdown", "metadata": {}, "source": ["## 6. Improved Deep Architecture & Focal Loss\n\nEnhancements:\n- **Deeper Architecture**: Added more capacity (256 -> 128 -> 64 -> 32 -> 16) to capture more complex non-linear combinations of features.\n- **Residual/Skip Connections**: Helps gradients flow reliably through deeper layers and prevents degradation.\n- **Focal Loss**: Replaces standard BCE. Focal loss mathematically down-weights 'easy' examples and heavily penalizes errors on the difficult minority class. Very effective for extreme class imbalance."]},
{"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "class ResidualBlock(nn.Module):\n",
    "    def __init__(self, in_features, out_features, dropout=0.3):\n",
    "        super().__init__()\n",
    "        self.fc = nn.Linear(in_features, out_features)\n",
    "        self.bn = nn.BatchNorm1d(out_features)\n",
    "        self.relu = nn.ReLU()\n",
    "        self.dropout = nn.Dropout(dropout)\n",
    "        \n",
    "        # Skip connection adapter if dimensionalities don't match\n",
    "        self.skip = nn.Linear(in_features, out_features) if in_features != out_features else nn.Identity()\n",
    "        \n",
    "    def forward(self, x):\n",
    "        identity = self.skip(x)\n",
    "        out = self.fc(x)\n",
    "        out = self.bn(out)\n",
    "        out = self.relu(out)\n",
    "        out = self.dropout(out)\n",
    "        return out + identity  # Skip connection\n",
    "\n",
    "class ImprovedReadmissionNet(nn.Module):\n",
    "    def __init__(self, input_dim):\n",
    "        super().__init__()\n",
    "        self.in_layer = nn.Sequential(\n",
    "            nn.Linear(input_dim, 256),\n",
    "            nn.BatchNorm1d(256),\n",
    "            nn.ReLU()\n",
    "        )\n",
    "        \n",
    "        # Deep residual blocks\n",
    "        self.res1 = ResidualBlock(256, 128, dropout=0.4)\n",
    "        self.res2 = ResidualBlock(128, 64, dropout=0.3)\n",
    "        self.res3 = ResidualBlock(64, 32, dropout=0.2)\n",
    "        \n",
    "        self.out_layer = nn.Sequential(\n",
    "            nn.Linear(32, 16),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(16, 1)\n",
    "            # Note: No Sigmoid here! We will use BCEWithLogitsLoss / FocalLoss which expects raw logits.\n",
    "        )\n",
    "\n",
    "    def forward(self, x):\n",
    "        x = self.in_layer(x)\n",
    "        x = self.res1(x)\n",
    "        x = self.res2(x)\n",
    "        x = self.res3(x)\n",
    "        x = self.out_layer(x)\n",
    "        return x.squeeze()\n",
    "\n",
    "model = ImprovedReadmissionNet(INPUT_DIM)\n",
    "print(f\"\\nTotal parameters: {sum(p.numel() for p in model.parameters()):,}\")"
]},

# ── SECTION 7: Advanced Training
{"cell_type": "markdown", "metadata": {}, "source": ["## 7. Training with Focal Loss Phase"]},
{"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "class FocalLoss(nn.Module):\n",
    "    def __init__(self, alpha=0.75, gamma=2.0, reduction='mean'):\n",
    "        super(FocalLoss, self).__init__()\n",
    "        self.alpha = alpha\n",
    "        self.gamma = gamma\n",
    "        self.reduction = reduction\n",
    "\n",
    "    def forward(self, inputs, targets):\n",
    "        BCE_loss = F.binary_cross_entropy_with_logits(inputs, targets, reduction='none')\n",
    "        pt = torch.exp(-BCE_loss) # Prevents nans when probability 0\n",
    "        F_loss = self.alpha * (1-pt)**self.gamma * BCE_loss\n",
    "\n",
    "        if self.reduction == 'mean': return torch.mean(F_loss)\n",
    "        elif self.reduction == 'sum': return torch.sum(F_loss)\n",
    "        else: return F_loss\n",
    "\n",
    "# Imbalance implies minority class needs more weight -> alpha controls this\n",
    "criterion = FocalLoss(alpha=0.80, gamma=2.0)\n",
    "\n",
    "optimizer = optim.AdamW(model.parameters(), lr=8e-4, weight_decay=1e-3)\n",
    "scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode=\"max\", factor=0.5, patience=8, verbose=True)"
]},
{"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "def train_one_epoch(model, loader, criterion, optimizer):\n",
    "    model.train()\n",
    "    total_loss, preds, labels = 0, [], []\n",
    "    for xb, yb in loader:\n",
    "        optimizer.zero_grad()\n",
    "        out = model(xb)\n",
    "        loss = criterion(out, yb)\n",
    "        loss.backward()\n",
    "        \n",
    "        # Gradient clipping to prevent exploding gradients in deeper nets\n",
    "        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)\n",
    "        \n",
    "        optimizer.step()\n",
    "        total_loss += loss.item() * xb.size(0)\n",
    "        \n",
    "        # Convert logits to probabilities for metrics\n",
    "        probs = torch.sigmoid(out).detach().cpu().numpy()\n",
    "        preds.extend(probs)\n",
    "        labels.extend(yb.cpu().numpy())\n",
    "        \n",
    "    avg_loss = total_loss / len(loader.dataset)\n",
    "    auc = roc_auc_score(labels, preds) if len(set(labels)) > 1 else 0.0\n",
    "    return avg_loss, auc\n",
    "\n",
    "def evaluate_model(model, loader):\n",
    "    model.eval()\n",
    "    total_loss, preds, labels = 0, [], []\n",
    "    val_criterion = FocalLoss(alpha=0.80, gamma=2.0)\n",
    "    with torch.no_grad():\n",
    "        for xb, yb in loader:\n",
    "            out = model(xb)\n",
    "            total_loss += val_criterion(out, yb).item() * xb.size(0)\n",
    "            probs = torch.sigmoid(out).cpu().numpy()\n",
    "            preds.extend(probs)\n",
    "            labels.extend(yb.cpu().numpy())\n",
    "            \n",
    "    avg_loss = total_loss / len(loader.dataset)\n",
    "    p, l = np.array(preds), np.array(labels)\n",
    "    auc_roc = roc_auc_score(l, p)          if len(set(labels)) > 1 else 0.0\n",
    "    auc_pr  = average_precision_score(l, p) if len(set(labels)) > 1 else 0.0\n",
    "    return avg_loss, auc_roc, auc_pr, p, l"
]},
{"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "EPOCHS  = 200\n",
    "PATIENCE = 25\n",
    "\n",
    "best_auc = 0.0\n",
    "wait     = 0\n",
    "hist = {\"tl\": [], \"vl\": [], \"ta\": [], \"va\": [], \"vp\": []}\n",
    "\n",
    "for epoch in range(EPOCHS):\n",
    "    tl, ta = train_one_epoch(model, train_loader, criterion, optimizer)\n",
    "    vl, va, vp, _, _ = evaluate_model(model, val_loader)\n",
    "\n",
    "    hist[\"tl\"].append(tl); hist[\"vl\"].append(vl)\n",
    "    hist[\"ta\"].append(ta); hist[\"va\"].append(va); hist[\"vp\"].append(vp)\n",
    "\n",
    "    scheduler.step(va)\n",
    "\n",
    "    if va > best_auc:\n",
    "        best_auc = va\n",
    "        wait = 0\n",
    "        torch.save(model.state_dict(), \"improved_best_model.pth\")\n",
    "    else:\n",
    "        wait += 1\n",
    "\n",
    "    if (epoch + 1) % 10 == 0:\n",
    "        print(f\"Epoch {epoch+1:3d}/{EPOCHS} | \"\n",
    "              f\"TrLoss: {tl:.4f} TrAUC: {ta:.4f} | \"\n",
    "              f\"VlLoss: {vl:.4f} VlAUC: {va:.4f} VlPR: {vp:.4f}\")\n",
    "\n",
    "    if wait >= PATIENCE:\n",
    "        print(f\"\\nEarly stopping at epoch {epoch+1}. Best AUC-ROC: {best_auc:.4f}\")\n",
    "        break\n",
    "\n",
    "print(f\"\\n✅ Training complete. Best val AUC-ROC: {best_auc:.4f}\")"
]},

# ── SECTION 8: Evaluation
{"cell_type": "markdown", "metadata": {}, "source": ["## 8. Evaluation & Threshold Tuning"]},
{"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "# Load best checkpoint\n",
    "model.load_state_dict(torch.load(\"improved_best_model.pth\"))\n",
    "_, val_auc_roc, val_auc_pr, val_preds, val_labels = evaluate_model(model, val_loader)\n",
    "\n",
    "print(f\"Val AUC-ROC: {val_auc_roc:.4f}\")\n",
    "print(f\"Val AUC-PR:  {val_auc_pr:.4f}\")"
]},
{"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "# Find optimal decision threshold by maximising F1 on validation set\n",
    "thresholds = np.arange(0.05, 0.90, 0.01)\n",
    "f1s = [f1_score(val_labels, (val_preds >= t).astype(int), zero_division=0) for t in thresholds]\n",
    "best_thresh = thresholds[np.argmax(f1s)]\n",
    "\n",
    "print(f\"Optimal threshold: {best_thresh:.2f}\")\n",
    "print(f\"Best F1:           {max(f1s):.4f}\")\n",
    "\n",
    "plt.figure(figsize=(8, 4))\n",
    "plt.plot(thresholds, f1s, color=\"#3498db\")\n",
    "plt.axvline(x=best_thresh, color=\"#e74c3c\", ls=\"--\", label=f\"Optimal: {best_thresh:.2f}\")\n",
    "plt.title(\"Threshold vs F1 Score\", fontsize=14, fontweight=\"bold\")\n",
    "plt.xlabel(\"Threshold\"); plt.ylabel(\"F1\")\n",
    "plt.legend(); plt.grid(True, alpha=0.3)\n",
    "plt.show()"
]},
{"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "# Final metrics at optimal threshold\n",
    "val_binary = (val_preds >= best_thresh).astype(int)\n",
    "\n",
    "print(\"=\" * 60)\n",
    "print(\"FINAL V2 (IMPROVED) VALIDATION RESULTS\")\n",
    "print(\"=\" * 60)\n",
    "print(f\"Threshold: {best_thresh:.2f}\")\n",
    "print(f\"AUC-ROC:   {val_auc_roc:.4f}\")\n",
    "print(f\"AUC-PR:    {val_auc_pr:.4f}\")\n",
    "print(f\"F1:        {f1_score(val_labels, val_binary):.4f}\")\n",
    "print(f\"Precision: {precision_score(val_labels, val_binary):.4f}\")\n",
    "print(f\"Recall:    {recall_score(val_labels, val_binary):.4f}\")\n",
    "print()\n",
    "print(classification_report(val_labels, val_binary, target_names=[\"Not Readmitted\", \"Readmitted\"]))"
]},

# ── SECTION 9: Test Predictions
{"cell_type": "markdown", "metadata": {}, "source": ["## 9. Test Set Predictions"]},
{"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
    "model.eval()\n",
    "with torch.no_grad():\n",
    "    test_out = model(X_test_t)\n",
    "    test_probs = torch.sigmoid(test_out).cpu().numpy()\n",
    "\n",
    "test_binary = (test_probs >= best_thresh).astype(int)\n",
    "\n",
    "print(f\"Test samples: {len(test_binary)}\")\n",
    "print(f\"Predicted positive: {test_binary.sum()} ({test_binary.mean()*100:.1f}%)\")\n",
    "print(f\"Predicted negative: {(1-test_binary).sum()} ({(1-test_binary.mean())*100:.1f}%)\")\n",
    "\n",
    "results = pd.DataFrame({\n",
    "    \"readmitted_30d_prob\": test_probs,\n",
    "    \"readmitted_30d_pred\": test_binary\n",
    "})\n",
    "results.to_csv(\"improved_test_predictions.csv\", index=False)\n",
    "print(\"\\n✅ Predictions saved to improved_test_predictions.csv\")"
]}

]

nb = {
 \"cells\": cells,
 \"metadata\": {
  \"kernelspec\": {\"display_name\": \"Python 3\", \"language\": \"python\", \"name\": \"python3\"},
  \"language_info\": {\"name\": \"python\", \"version\": \"3.10.0\"}
 },
 \"nbformat\": 4,
 \"nbformat_minor\": 4
}

out_path = os.path.join(\"notebooks\", \"improved_solution.ipynb\")
with open(out_path, \"w\") as f:
    json.dump(nb, f, indent=1)
print(f\"{out_path} created successfully!\")
print(f\"Total cells: {len(cells)}\")
